service:
  name: news-api-{self.provider.stage}

custom:
# Our stage is based on what is passed in when running serverless
# commands. Or fallsback to what we have set in the provider section.
stage: ${opt:stage, self:provider.stage}

plugins:
  - serverless-webpack
provider:
  name: ${file(../../serverless.common.yml):provider-name}
  runtime: ${file(../../serverless.common.yml):runtime}
  stage: dev
  region: ${file(../../serverless.common.yml):region}

functions:
  news:
    handler: handler.news
    events:
      - http:
          method: get
          path: news
