service:
  name: news-api-${self:custom.stage}

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}

plugins:
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1

functions:
  news:
    handler: handler.news
    events:
      - http:
          method: get
          path: news
