name: News Api Dev CI/CD

on:
  push:
    branches:
      - develop
    paths:
      - "services/news/*"

jobs:
  primary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install dependencies
        run: yarn install
      - name: serverless deploy
        run: |
          cd services/news
          npx serverless deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
